baseURL: "https://yayapipi.github.io/"
title: Yayapipi Site
paginate: 100
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

taxonomies:
  category: categories
  tag: tags
  story: storys
  project: projects

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Yayapipi Site
    description: "Yayapipi Developer Site"
    author: Yayapipi
    # author: ["Me", "You"] # multiple authors

    images: "<link or path of image for opengraph, twitter-cards>"

    ShowReadingTime: true
    ShowShareButtons: true
    comments: false
    defaultTheme: dark
    disableThemeToggle: false
    disableSpecial1stPost: false

    assets:
        favicon: "favicon.png"
        favicon16x16: "favicon16.png"
        favicon32x32: "favicon32.png"
        apple_touch_icon: "favicon.png"
        safari_pinned_tab: "favicon.png"

    label:
        text: "Yayapipi Site"
        #icon: logo.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Yayapipi Site
        imageUrl: 'logo.png'
        imageTitle: Yayapipi Logo
        buttons:
            - name: 作品
              url: products
            - name: 文章
              url: posts
           # - name: 標簽
           #   url: tags

    # home-info mode
    homeInfoParams:
        Title: "Yayapipi Site \U0001F44B"
        Content: Welcome

    socialIcons:
        - name: email
          url: "mailto:yayapipi@hotmail.com"
        - name: facebook
          url: "https://facebook.com/yayapipistudio"
        - name: github
          url: "https://github.com/yayapipi"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
markup:
  goldmark:
    renderer:
      unsafe: false